### ISSUE TITLE
Windows gVim 8.1.1 - "phpactor returned an error"

### ISSUE THREAD

**Issue by antaed** [phpactor/phpactor#564]
Hi,
Any idea why I get the error below when I issue the` :call phpactor#Status()` command?

<img src="https://user-images.githubusercontent.com/30736986/44106920-9289060a-9ffe-11e8-815c-28ec16ef7220.png" alt="screenshot" width="360"/>

I installed the plugin with minpac and the dependencies manually, inside the phpactor directory.
Thanks!

**Comment by dantleech** [comment]
Hmm, which version of VIM (`vim --version` / `gvim --version`) ?

**Comment by antaed** [comment]
VIM - Vi IMproved 8.1 (2018 May 18, compiled May 18 
2018 18:36:07)
MS-Windows 32-bit GUI version with OLE support
Included patches: 1
Compiled by mool@tororo
Huge version with GUI.  Features included (+) or not (-):
+acl                +emacs_tags         +mouse              
+tag_binary
+arabic             +eval               +mouseshape         
+tag_old_static
+autocmd            +ex_extra           +multi_byte_ime/dy
n -tag_any_white
+autoservername     +extra_search       +multi_lang

**Comment by dantleech** [comment]
Could you open the VIM plugin (e.g. `.vim/<bundle directory>/phpactor/plugin/phpactor.vim`, not sure where this is with your setup) and debug the request which should be sent to Phpactor?

After the following:

```vim
function! phpactor#rpc(action, arguments)
    " Remove any existing output in the message window
    execute ':redraw'

    let request = { "action": a:action, "parameters": a:arguments }

    let cmd = g:phpactorPhpBin . ' ' . g:phpactorbinpath . ' rpc --working-dir=' . g:phpactorInitialCwd
    let result = system(cmd, json_encode(request))
```

add:

```vim
    call confirm(json_encode(request))
```

then it should show the request data for the request when you call the `Status` command (or any other).

(the error message you are getting should show the JSON received, but it seems to show that no data was sent at all over STDIN).

**Comment by dantleech** [comment]
Hmm, I am suspecting it might be an issue with reading from STDIN, not sure though.

Maybe try creating a PHP script `test.php`:

```
<?php

var_dump(fgets(STDIN));
```

and running the equivilent on Windows:

```
$ echo "Hello World" | php test.php
```

?

**Comment by dantleech** [comment]
ok, then perhaps try this: in `lib/Extension/Rpc/Command/RpcCommand.php`, after:

```
    public function execute(InputInterface $input, OutputInterface $output)
    {
        $stdin = $this->resolveInput($input->getOption('replay'));
```

```
throw new \Exception("STDIN: ".$stdin);
```

?

**Comment by dantleech** [comment]
So:

- VIM is passing the request to the `system` call to Phpactor.
- Phpactor shis reading from STDIN correctly.

But Phpactor is not receiving the message - you might additionally try from the command line:

```
$ echo '{"action":"echo","parameters":{"message":"Hello World"}}' | ./bin/phpactor rpc
```

But it seems to be a problem with communication from GVim to Phpactor. Have you tried from the normal console version of `vim` ?

**Comment by dantleech** [comment]
hmm, this looks like a VIM environment problem in Windows, at least from the CLI version. [This google search](https://www.google.co.uk/search?biw=2556&bih=1367&ei=jWN0W8_fLMXSwQLimrbIAg&q=vim81+was+unexpected+at+this+time&oq=vim81+was+unexpected+at+this+time&gs_l=psy-ab.3...7036.7036.0.7220.1.1.0.0.0.0.69.69.1.1.0....0...1c.1.64.psy-ab..0.0.0....0.Pp2rvNfN14Y) indicates that this _might_ be a problem with your `.bat` files I guess.

You could also try running the "[Linux Subsystem for Windows](https://conemu.github.io/en/BashOnWindows.html)".

Unfortunately I don't have access to a Windows box, so I can't test this further. Please update if you get any further :)

**Comment by antaed** [comment]
Not a big deal for me tbh because I use macVim at work. I wanted to be able to use the plugin on my home PC but I would only need it occasionally anyway.
Thanks for your fantastic work and for your help so far.

**Comment by dalibor983** [comment]
This plugin does not work at all in windows environment because it cannot find files with windows style paths `e:\this\that/.phpactor.json`. Error:
```
Path is not absolute "e:\this\that/.phpactor.json"
```

This is error I get when run `:call phpactor#Status()`

**Comment by haohetao** [comment]
same problem

**Comment by dantleech** [comment]
I don't have Windows, so it's difficult for me to address this issue. It would be good to run the `status` command with `-vvv` to get the stack trace, I could then try and fix the issue.

**Comment by haohetao** [comment]
![20200708161513](https://user-images.githubusercontent.com/4592571/86905769-21ab4c80-c145-11ea-9a51-235ee105cd8b.png)

**Comment by haohetao** [comment]
@dantleech 
this is in gvim,i have not status command

**Comment by haohetao** [comment]
```:call phpactor#Status()```

![QQ截图20200708182209](https://user-images.githubusercontent.com/4592571/86907682-04c44880-c148-11ea-9e25-75af094f2d92.png)

**Comment by dantleech** [comment]
Sorry, I meant from the terminal:

```
$ /path/to/phpactor status -vvv
```

**Comment by haohetao** [comment]
> Array
(
    [0] => Array
        (
            [file] => C:\Users\hetao\.vim\plugged\phpactor\vendor\phpactor\config-loader\lib\ConfigLoaderBuilder.php
            [line] => 52
            [function] => __construct
            [class] => Phpactor\ConfigLoader\Adapter\PathCandidate\AbsolutePathCandidate
            [object] => Phpactor\ConfigLoader\Adapter\PathCandidate\AbsolutePathCandidate Object
                (
                    [absolutePath:Phpactor\ConfigLoader\Adapter\PathCandidate\AbsolutePathCandidate:private] => C:\Users\hetao\.vim\plugged\phpactor/.phpactor.json
                    [loader:Phpactor\ConfigLoader\Adapter\PathCandidate\AbsolutePathCandidate:private] => json
                )

            [type] => ->
            [args] => Array
                (
                    [0] => C:\Users\hetao\.vim\plugged\phpactor/.phpactor.json
                    [1] => json
                )

        )

    [1] => Array
        (
            [file] => C:\Users\hetao\.vim\plugged\phpactor\lib\Phpactor.php
            [line] => 70
            [function] => addCandidate
            [class] => Phpactor\ConfigLoader\ConfigLoaderBuilder
            [object] => Phpactor\ConfigLoader\ConfigLoaderBuilder Object
                (
                    [serializers:Phpactor\ConfigLoader\ConfigLoaderBuilder:private] => Array
                        (
                            [json] => Phpactor\ConfigLoader\Adapter\Deserializer\JsonDeserializer Object
                                (
                                )

                            [yaml] => Phpactor\ConfigLoader\Adapter\Deserializer\YamlDeserializer Object
                                (
                                    [parser:Phpactor\ConfigLoader\Adapter\Deserializer\YamlDeserializer:private] => Symfony\Component\Yaml\Parser Object
                                        (
                                            [filename:Symfony\Component\Yaml\Parser:private] =>
                                            [offset:Symfony\Component\Yaml\Parser:private] => 0
                                            [totalNumberOfLines:Symfony\Component\Yaml\Parser:private] =>
                                            [lines:Symfony\Component\Yaml\Parser:private] => Array
                                                (
                                                )

                                            [currentLineNb:Symfony\Component\Yaml\Parser:private] => -1
                                            [currentLine:Symfony\Component\Yaml\Parser:private] =>
                                            [refs:Symfony\Component\Yaml\Parser:private] => Array
                                                (
                                                )

                                            [skippedLineNumbers:Symfony\Component\Yaml\Parser:private] => Array
                                                (
                                                )

                                            [locallySkippedLineNumbers:Symfony\Component\Yaml\Parser:private] => Array
                                                (
                                                )

                                            [refsBeingParsed:Symfony\Component\Yaml\Parser:private] => Array
                                                (
                                                )

                                        )

                                )

                        )

                    [candidates:Phpactor\ConfigLoader\ConfigLoaderBuilder:private] => Array
                        (
                            [0] => Phpactor\ConfigLoader\Adapter\PathCandidate\XdgPathCandidate Object
                                (
                                    [xdg:Phpactor\ConfigLoader\Adapter\PathCandidate\XdgPathCandidate:private] => XdgBaseDir\Xdg Object
                                        (
                                        )

                                    [filename:Phpactor\ConfigLoader\Adapter\PathCandidate\XdgPathCandidate:private] => phpactor.json
                                    [loader:Phpactor\ConfigLoader\Adapter\PathCandidate\XdgPathCandidate:private] => json
                                    [appName:Phpactor\ConfigLoader\Adapter\PathCandidate\XdgPathCandidate:private] => phpactor
                                )

                            [1] => Phpactor\ConfigLoader\Adapter\PathCandidate\XdgPathCandidate Object
                                (
                                    [xdg:Phpactor\ConfigLoader\Adapter\PathCandidate\XdgPathCandidate:private] => XdgBaseDir\Xdg Object
                                        (
                                        )

                                    [filename:Phpactor\ConfigLoader\Adapter\PathCandidate\XdgPathCandidate:private] => phpactor.yml
                                    [loader:Phpactor\ConfigLoader\Adapter\PathCandidate\XdgPathCandidate:private] => yaml
                                    [appName:Phpactor\ConfigLoader\Adapter\PathCandidate\XdgPathCandidate:private] => phpactor
                                )

                        )

                )

            [type] => ->
            [args] => Array
                (
                    [0] => C:\Users\hetao\.vim\plugged\phpactor/.phpactor.json
                    [1] => json
                )

        )

    [2] => Array
        (
            [file] => C:\Users\hetao\.vim\plugged\phpactor\lib\Application.php
            [line] => 111
            [function] => boot
            [class] => Phpactor\Phpactor
            [type] => ::
            [args] => Array
                (
                    [0] => Symfony\Component\Console\Input\ArgvInput Object
                        (
                            [tokens:Symfony\Component\Console\Input\ArgvInput:private] => Array
                                (
                                )

                            [parsed:Symfony\Component\Console\Input\ArgvInput:private] =>
                            [definition:protected] => Symfony\Component\Console\Input\InputDefinition Object
                                (
                                    [arguments:Symfony\Component\Console\Input\InputDefinition:private] => Array
                                        (
                                        )

                                    [requiredCount:Symfony\Component\Console\Input\InputDefinition:private] => 0
                                    [hasAnArrayArgument:Symfony\Component\Console\Input\InputDefinition:private] =>
                                    [hasOptional:Symfony\Component\Console\Input\InputDefinition:private] =>
                                    [options:Symfony\Component\Console\Input\InputDefinition:private] => Array
                                        (
                                        )

                                    [shortcuts:Symfony\Component\Console\Input\InputDefinition:private] => Array
                                        (
                                        )

                                )

                            [stream:protected] =>
                            [options:protected] => Array
                                (
                                )

                            [arguments:protected] => Array
                                (
                                )

                            [interactive:protected] => 1
                        )

                    [1] => C:\Users\hetao\.vim\plugged\phpactor\vendor
                )

        )

    [3] => Array
        (
            [file] => C:\Users\hetao\.vim\plugged\phpactor\lib\Application.php
            [line] => 38
            [function] => initialize
            [class] => Phpactor\Application
            [object] => Phpactor\Application Object
                (
                    [container:Phpactor\Application:private] =>
                    [vendorDir:Phpactor\Application:private] => C:\Users\hetao\.vim\plugged\phpactor\vendor
                    [commands:Symfony\Component\Console\Application:private] => Array
                        (
                        )

                    [wantHelps:Symfony\Component\Console\Application:private] =>
                    [runningCommand:Symfony\Component\Console\Application:private] =>
                    [name:Symfony\Component\Console\Application:private] => Phpactor
                    [version:Symfony\Component\Console\Application:private] => dev-master@111c3e6a7d23ace915b4e01a6d77e4445182ff70
                    [commandLoader:Symfony\Component\Console\Application:private] =>
                    [catchExceptions:Symfony\Component\Console\Application:private] => 1
                    [autoExit:Symfony\Component\Console\Application:private] => 1
                    [definition:Symfony\Component\Console\Application:private] =>
                    [helperSet:Symfony\Component\Console\Application:private] =>
                    [dispatcher:Symfony\Component\Console\Application:private] =>
                    [terminal:Symfony\Component\Console\Application:private] => Symfony\Component\Console\Terminal Object
                        (
                        )

                    [defaultCommand:Symfony\Component\Console\Application:private] => list
                    [singleCommand:Symfony\Component\Console\Application:private] =>
                    [initialized:Symfony\Component\Console\Application:private] =>
                )

            [type] => ->
            [args] => Array
                (
                    [0] => Symfony\Component\Console\Input\ArgvInput Object
                        (
                            [tokens:Symfony\Component\Console\Input\ArgvInput:private] => Array
                                (
                                )

                            [parsed:Symfony\Component\Console\Input\ArgvInput:private] =>
                            [definition:protected] => Symfony\Component\Console\Input\InputDefinition Object
                                (
                                    [arguments:Symfony\Component\Console\Input\InputDefinition:private] => Array
                                        (
                                        )

                                    [requiredCount:Symfony\Component\Console\Input\InputDefinition:private] => 0
                                    [hasAnArrayArgument:Symfony\Component\Console\Input\InputDefinition:private] =>
                                    [hasOptional:Symfony\Component\Console\Input\InputDefinition:private] =>
                                    [options:Symfony\Component\Console\Input\InputDefinition:private] => Array
                                        (
                                        )

                                    [shortcuts:Symfony\Component\Console\Input\InputDefinition:private] => Array
                                        (
                                        )

                                )

                            [stream:protected] =>
                            [options:protected] => Array
                                (
                                )

                            [arguments:protected] => Array
                                (
                                )

                            [interactive:protected] => 1
                        )

                )

        )

    [4] => Array
        (
            [file] => C:\Users\hetao\.vim\plugged\phpactor\vendor\symfony\console\Application.php
            [line] => 147
            [function] => doRun
            [class] => Phpactor\Application
            [object] => Phpactor\Application Object
                (
                    [container:Phpactor\Application:private] =>
                    [vendorDir:Phpactor\Application:private] => C:\Users\hetao\.vim\plugged\phpactor\vendor
                    [commands:Symfony\Component\Console\Application:private] => Array
                        (
                        )

                    [wantHelps:Symfony\Component\Console\Application:private] =>
                    [runningCommand:Symfony\Component\Console\Application:private] =>
                    [name:Symfony\Component\Console\Application:private] => Phpactor
                    [version:Symfony\Component\Console\Application:private] => dev-master@111c3e6a7d23ace915b4e01a6d77e4445182ff70
                    [commandLoader:Symfony\Component\Console\Application:private] =>
                    [catchExceptions:Symfony\Component\Console\Application:private] => 1
                    [autoExit:Symfony\Component\Console\Application:private] => 1
                    [definition:Symfony\Component\Console\Application:private] =>
                    [helperSet:Symfony\Component\Console\Application:private] =>
                    [dispatcher:Symfony\Component\Console\Application:private] =>
                    [terminal:Symfony\Component\Console\Application:private] => Symfony\Component\Console\Terminal Object
                        (
                        )

                    [defaultCommand:Symfony\Component\Console\Application:private] => list
                    [singleCommand:Symfony\Component\Console\Application:private] =>
                    [initialized:Symfony\Component\Console\Application:private] =>
                )

            [type] => ->
            [args] => Array
                (
                    [0] => Symfony\Component\Console\Input\ArgvInput Object
                        (
                            [tokens:Symfony\Component\Console\Input\ArgvInput:private] => Array
                                (
                                )

                            [parsed:Symfony\Component\Console\Input\ArgvInput:private] =>
                            [definition:protected] => Symfony\Component\Console\Input\InputDefinition Object
                                (
                                    [arguments:Symfony\Component\Console\Input\InputDefinition:private] => Array
                                        (
                                        )

                                    [requiredCount:Symfony\Component\Console\Input\InputDefinition:private] => 0
                                    [hasAnArrayArgument:Symfony\Component\Console\Input\InputDefinition:private] =>
                                    [hasOptional:Symfony\Component\Console\Input\InputDefinition:private] =>
                                    [options:Symfony\Component\Console\Input\InputDefinition:private] => Array
                                        (
                                        )

                                    [shortcuts:Symfony\Component\Console\Input\InputDefinition:private] => Array
                                        (
                                        )

                                )

                            [stream:protected] =>
                            [options:protected] => Array
                                (
                                )

                            [arguments:protected] => Array
                                (
                                )

                            [interactive:protected] => 1
                        )

                    [1] => Symfony\Component\Console\Output\ConsoleOutput Object
                        (
                            [stderr:Symfony\Component\Console\Output\ConsoleOutput:private] => Symfony\Component\Console\Output\StreamOutput Object
                                (
                                    [stream:Symfony\Component\Console\Output\StreamOutput:private] => Resource id #248
                                    [verbosity:Symfony\Component\Console\Output\Output:private] => 32
                                    [formatter:Symfony\Component\Console\Output\Output:private] => Symfony\Component\Console\Formatter\OutputFormatter Object
                                        (
                                            [decorated:Symfony\Component\Console\Formatter\OutputFormatter:private] => 1
                                            [styles:Symfony\Component\Console\Formatter\OutputFormatter:private] => Array
                                                (
                                                    [error] => Symfony\Component\Console\Formatter\OutputFormatterStyle Object
                                                        (
                                                            [foreground:Symfony\Component\Console\Formatter\OutputFormatterStyle:private] => Array
                                                                (
                                                                    [set] => 37
                                                                    [unset] => 39
                                                                )

                                                            [background:Symfony\Component\Console\Formatter\OutputFormatterStyle:private] => Array
                                                                (
                                                                    [set] => 41
                                                                    [unset] => 49
                                                                )

                                                            [href:Symfony\Component\Console\Formatter\OutputFormatterStyle:private] =>
                                                            [options:Symfony\Component\Console\Formatter\OutputFormatterStyle:private] => Array
                                                                (
                                                                )

                                                            [handlesHrefGracefully:Symfony\Component\Console\Formatter\OutputFormatterStyle:private] =>
                                                        )

                                                    [info] => Symfony\Component\Console\Formatter\OutputFormatterStyle Object
                                                        (
                                                            [foreground:Symfony\Component\Console\Formatter\OutputFormatterStyle:private] => Array
                                                                (
                                                                    [set] => 32
                                                                    [unset] => 39
                                                                )

                                                            [background:Symfony\Component\Console\Formatter\OutputFormatterStyle:private] =>
                                                            [href:Symfony\Component\Console\Formatter\OutputFormatterStyle:private] =>
                                                            [options:Symfony\Component\Console\Formatter\OutputFormatterStyle:private] => Array
                                                                (
                                                                )

                                                            [handlesHrefGracefully:Symfony\Component\Console\Formatter\OutputFormatterStyle:private] =>
                                                        )

                                                    [comment] => Symfony\Component\Console\Formatter\OutputFormatterStyle Object
                                                        (
                                                            [foreground:Symfony\Component\Console\Formatter\OutputFormatterStyle:private] => Array
                                                                (
                                                                    [set] => 33
                                                                    [unset] => 39
                                                                )

                                                            [background:Symfony\Component\Console\Formatter\OutputFormatterStyle:private] =>
                                                            [href:Symfony\Component\Console\Formatter\OutputFormatterStyle:private] =>
                                                            [options:Symfony\Component\Console\Formatter\OutputFormatterStyle:private] => Array
                                                                (
                                                                )

                                                            [handlesHrefGracefully:Symfony\Component\Console\Formatter\OutputFormatterStyle:private] =>
                                                        )

                                                    [question] => Symfony\Component\Console\Formatter\OutputFormatterStyle Object
                                                        (
                                                            [foreground:Symfony\Component\Console\Formatter\OutputFormatterStyle:private] => Array
                                                                (
                                                                    [set] => 30
                                                                    [unset] => 39
                                                                )

                                                            [background:Symfony\Component\Console\Formatter\OutputFormatterStyle:private] => Array
                                                                (
                                                                    [set] => 46
                                                                    [unset] => 49
                                                                )

                                                            [href:Symfony\Component\Console\Formatter\OutputFormatterStyle:private] =>
                                                            [options:Symfony\Component\Console\Formatter\OutputFormatterStyle:private] => Array
                                                                (
                                                                )

                                                            [handlesHrefGracefully:Symfony\Component\Console\Formatter\OutputFormatterStyle:private] =>
                                                        )

                                                )

                                            [styleStack:Symfony\Component\Console\Formatter\OutputFormatter:private] => Symfony\Component\Console\Formatter\OutputFormatterStyleStack Object
                                                (
                                                    [styles:Symfony\Component\Console\Formatter\OutputFormatterStyleStack:private] => Array
                                                        (
                                                        )

                                                    [emptyStyle:Symfony\Component\Console\Formatter\OutputFormatterStyleStack:private] => Symfony\Component\Console\Formatter\OutputFormatterStyle Object
                                                        (
                                                            [foreground:Symfony\Component\Console\Formatter\OutputFormatterStyle:private] =>
                                                            [background:Symfony\Component\Console\Formatter\OutputFormatterStyle:private] =>
                                                            [href:Symfony\Component\Console\Formatter\OutputFormatterStyle:private] =>
                                                            [options:Symfony\Component\Console\Formatter\OutputFormatterStyle:private] => Array
                                                                (
                                                                )

                                                            [handlesHrefGracefully:Symfony\Component\Console\Formatter\OutputFormatterStyle:private] =>
                                                        )

                                                )

                                        )

                                )

                            [consoleSectionOutputs:Symfony\Component\Console\Output\ConsoleOutput:private] => Array
                                (
                                )

                            [stream:Symfony\Component\Console\Output\StreamOutput:private] => Resource id #241
                            [verbosity:Symfony\Component\Console\Output\Output:private] => 32
                            [formatter:Symfony\Component\Console\Output\Output:private] => Symfony\Component\Console\Formatter\OutputFormatter Object
                                (
                                    [decorated:Symfony\Component\Console\Formatter\OutputFormatter:private] => 1
                                    [styles:Symfony\Component\Console\Formatter\OutputFormatter:private] => Array
                                        (
                                            [error] => Symfony\Component\Console\Formatter\OutputFormatterStyle Object
                                                (
                                                    [foreground:Symfony\Component\Console\Formatter\OutputFormatterStyle:private] => Array
                                                        (
                                                            [set] => 37
                                                            [unset] => 39
                                                        )

                                                    [background:Symfony\Component\Console\Formatter\OutputFormatterStyle:private] => Array
                                                        (
                                                            [set] => 41
                                                            [unset] => 49
                                                        )

                                                    [href:Symfony\Component\Console\Formatter\OutputFormatterStyle:private] =>
                                                    [options:Symfony\Component\Console\Formatter\OutputFormatterStyle:private] => Array
                                                        (
                                                        )

                                                    [handlesHrefGracefully:Symfony\Component\Console\Formatter\OutputFormatterStyle:private] =>
                                                )

                                            [info] => Symfony\Component\Console\Formatter\OutputFormatterStyle Object
                                                (
                                                    [foreground:Symfony\Component\Console\Formatter\OutputFormatterStyle:private] => Array
                                                        (
                                                            [set] => 32
                                                            [unset] => 39
                                                        )

                                                    [background:Symfony\Component\Console\Formatter\OutputFormatterStyle:private] =>
                                                    [href:Symfony\Component\Console\Formatter\OutputFormatterStyle:private] =>
                                                    [options:Symfony\Component\Console\Formatter\OutputFormatterStyle:private] => Array
                                                        (
                                                        )

                                                    [handlesHrefGracefully:Symfony\Component\Console\Formatter\OutputFormatterStyle:private] =>
                                                )

                                            [comment] => Symfony\Component\Console\Formatter\OutputFormatterStyle Object
                                                (
                                                    [foreground:Symfony\Component\Console\Formatter\OutputFormatterStyle:private] => Array
                                                        (
                                                            [set] => 33
                                                            [unset] => 39
                                                        )

                                                    [background:Symfony\Component\Console\Formatter\OutputFormatterStyle:private] =>
                                                    [href:Symfony\Component\Console\Formatter\OutputFormatterStyle:private] =>
                                                    [options:Symfony\Component\Console\Formatter\OutputFormatterStyle:private] => Array
                                                        (
                                                        )

                                                    [handlesHrefGracefully:Symfony\Component\Console\Formatter\OutputFormatterStyle:private] =>
                                                )

                                            [question] => Symfony\Component\Console\Formatter\OutputFormatterStyle Object
                                                (
                                                    [foreground:Symfony\Component\Console\Formatter\OutputFormatterStyle:private] => Array
                                                        (
                                                            [set] => 30
                                                            [unset] => 39
                                                        )

                                                    [background:Symfony\Component\Console\Formatter\OutputFormatterStyle:private] => Array
                                                        (
                                                            [set] => 46
                                                            [unset] => 49
                                                        )

                                                    [href:Symfony\Component\Console\Formatter\OutputFormatterStyle:private] =>
                                                    [options:Symfony\Component\Console\Formatter\OutputFormatterStyle:private] => Array
                                                        (
                                                        )

                                                    [handlesHrefGracefully:Symfony\Component\Console\Formatter\OutputFormatterStyle:private] =>
                                                )

                                        )

                                    [styleStack:Symfony\Component\Console\Formatter\OutputFormatter:private] => Symfony\Component\Console\Formatter\OutputFormatterStyleStack Object
                                        (
                                            [styles:Symfony\Component\Console\Formatter\OutputFormatterStyleStack:private] => Array
                                                (
                                                )

                                            [emptyStyle:Symfony\Component\Console\Formatter\OutputFormatterStyleStack:private] => Symfony\Component\Console\Formatter\OutputFormatterStyle Object
                                                (
                                                    [foreground:Symfony\Component\Console\Formatter\OutputFormatterStyle:private] =>
                                                    [background:Symfony\Component\Console\Formatter\OutputFormatterStyle:private] =>
                                                    [href:Symfony\Component\Console\Formatter\OutputFormatterStyle:private] =>
                                                    [options:Symfony\Component\Console\Formatter\OutputFormatterStyle:private] => Array
                                                        (
                                                        )

                                                    [handlesHrefGracefully:Symfony\Component\Console\Formatter\OutputFormatterStyle:private] =>
                                                )

                                        )

                                )

                        )

                )

        )

    [5] => Array
        (
            [file] => C:\Users\hetao\.vim\plugged\phpactor\bin\phpactor
            [line] => 43
            [function] => run
            [class] => Symfony\Component\Console\Application
            [object] => Phpactor\Application Object
                (
                    [container:Phpactor\Application:private] =>
                    [vendorDir:Phpactor\Application:private] => C:\Users\hetao\.vim\plugged\phpactor\vendor
                    [commands:Symfony\Component\Console\Application:private] => Array
                        (
                        )

                    [wantHelps:Symfony\Component\Console\Application:private] =>
                    [runningCommand:Symfony\Component\Console\Application:private] =>
                    [name:Symfony\Component\Console\Application:private] => Phpactor
                    [version:Symfony\Component\Console\Application:private] => dev-master@111c3e6a7d23ace915b4e01a6d77e4445182ff70
                    [commandLoader:Symfony\Component\Console\Application:private] =>
                    [catchExceptions:Symfony\Component\Console\Application:private] => 1
                    [autoExit:Symfony\Component\Console\Application:private] => 1
                    [definition:Symfony\Component\Console\Application:private] =>
                    [helperSet:Symfony\Component\Console\Application:private] =>
                    [dispatcher:Symfony\Component\Console\Application:private] =>
                    [terminal:Symfony\Component\Console\Application:private] => Symfony\Component\Console\Terminal Object
                        (
                        )

                    [defaultCommand:Symfony\Component\Console\Application:private] => list
                    [singleCommand:Symfony\Component\Console\Application:private] =>
                    [initialized:Symfony\Component\Console\Application:private] =>
                )

            [type] => ->
            [args] => Array
                (
                    [0] => Symfony\Component\Console\Input\ArgvInput Object
                        (
                            [tokens:Symfony\Component\Console\Input\ArgvInput:private] => Array
                                (
                                )

                            [parsed:Symfony\Component\Console\Input\ArgvInput:private] =>
                            [definition:protected] => Symfony\Component\Console\Input\InputDefinition Object
                                (
                                    [arguments:Symfony\Component\Console\Input\InputDefinition:private] => Array
                                        (
                                        )

                                    [requiredCount:Symfony\Component\Console\Input\InputDefinition:private] => 0
                                    [hasAnArrayArgument:Symfony\Component\Console\Input\InputDefinition:private] =>
                                    [hasOptional:Symfony\Component\Console\Input\InputDefinition:private] =>
                                    [options:Symfony\Component\Console\Input\InputDefinition:private] => Array
                                        (
                                        )

                                    [shortcuts:Symfony\Component\Console\Input\InputDefinition:private] => Array
                                        (
                                        )

                                )

                            [stream:protected] =>
                            [options:protected] => Array
                                (
                                )

                            [arguments:protected] => Array
                                (
                                )

                            [interactive:protected] => 1
                        )

                    [1] => Symfony\Component\Console\Output\ConsoleOutput Object
                        (
                            [stderr:Symfony\Component\Console\Output\ConsoleOutput:private] => Symfony\Component\Console\Output\StreamOutput Object
                                (
                                    [stream:Symfony\Component\Console\Output\StreamOutput:private] => Resource id #248
                                    [verbosity:Symfony\Component\Console\Output\Output:private] => 32
                                    [formatter:Symfony\Component\Console\Output\Output:private] => Symfony\Component\Console\Formatter\OutputFormatter Object
                                        (
                                            [decorated:Symfony\Component\Console\Formatter\OutputFormatter:private] => 1
                                            [styles:Symfony\Component\Console\Formatter\OutputFormatter:private] => Array
                                                (
                                                    [error] => Symfony\Component\Console\Formatter\OutputFormatterStyle Object
                                                        (
                                                            [foreground:Symfony\Component\Console\Formatter\OutputFormatterStyle:private] => Array
                                                                (
                                                                    [set] => 37
                                                                    [unset] => 39
                                                                )

                                                            [background:Symfony\Component\Console\Formatter\OutputFormatterStyle:private] => Array
                                                                (
                                                                    [set] => 41
                                                                    [unset] => 49
                                                                )

                                                            [href:Symfony\Component\Console\Formatter\OutputFormatterStyle:private] =>
                                                            [options:Symfony\Component\Console\Formatter\OutputFormatterStyle:private] => Array
                                                                (
                                                                )

                                                            [handlesHrefGracefully:Symfony\Component\Console\Formatter\OutputFormatterStyle:private] =>
                                                        )

                                                    [info] => Symfony\Component\Console\Formatter\OutputFormatterStyle Object
                                                        (
                                                            [foreground:Symfony\Component\Console\Formatter\OutputFormatterStyle:private] => Array
                                                                (
                                                                    [set] => 32
                                                                    [unset] => 39
                                                                )

                                                            [background:Symfony\Component\Console\Formatter\OutputFormatterStyle:private] =>
                                                            [href:Symfony\Component\Console\Formatter\OutputFormatterStyle:private] =>
                                                            [options:Symfony\Component\Console\Formatter\OutputFormatterStyle:private] => Array
                                                                (
                                                                )

                                                            [handlesHrefGracefully:Symfony\Component\Console\Formatter\OutputFormatterStyle:private] =>
                                                        )

                                                    [comment] => Symfony\Component\Console\Formatter\OutputFormatterStyle Object
                                                        (
                                                            [foreground:Symfony\Component\Console\Formatter\OutputFormatterStyle:private] => Array
                                                                (
                                                                    [set] => 33
                                                                    [unset] => 39
                                                                )

                                                            [background:Symfony\Component\Console\Formatter\OutputFormatterStyle:private] =>
                                                            [href:Symfony\Component\Console\Formatter\OutputFormatterStyle:private] =>
                                                            [options:Symfony\Component\Console\Formatter\OutputFormatterStyle:private] => Array
                                                                (
                                                                )

                                                            [handlesHrefGracefully:Symfony\Component\Console\Formatter\OutputFormatterStyle:private] =>
                                                        )

                                                    [question] => Symfony\Component\Console\Formatter\OutputFormatterStyle Object
                                                        (
                                                            [foreground:Symfony\Component\Console\Formatter\OutputFormatterStyle:private] => Array
                                                                (
                                                                    [set] => 30
                                                                    [unset] => 39
                                                                )

                                                            [background:Symfony\Component\Console\Formatter\OutputFormatterStyle:private] => Array
                                                                (
                                                                    [set] => 46
                                                                    [unset] => 49
                                                                )

                                                            [href:Symfony\Component\Console\Formatter\OutputFormatterStyle:private] =>
                                                            [options:Symfony\Component\Console\Formatter\OutputFormatterStyle:private] => Array
                                                                (
                                                                )

                                                            [handlesHrefGracefully:Symfony\Component\Console\Formatter\OutputFormatterStyle:private] =>
                                                        )

                                                )

                                            [styleStack:Symfony\Component\Console\Formatter\OutputFormatter:private] => Symfony\Component\Console\Formatter\OutputFormatterStyleStack Object
                                                (
                                                    [styles:Symfony\Component\Console\Formatter\OutputFormatterStyleStack:private] => Array
                                                        (
                                                        )

                                                    [emptyStyle:Symfony\Component\Console\Formatter\OutputFormatterStyleStack:private] => Symfony\Component\Console\Formatter\OutputFormatterStyle Object
                                                        (
                                                            [foreground:Symfony\Component\Console\Formatter\OutputFormatterStyle:private] =>
                                                            [background:Symfony\Component\Console\Formatter\OutputFormatterStyle:private] =>
                                                            [href:Symfony\Component\Console\Formatter\OutputFormatterStyle:private] =>
                                                            [options:Symfony\Component\Console\Formatter\OutputFormatterStyle:private] => Array
                                                                (
                                                                )

                                                            [handlesHrefGracefully:Symfony\Component\Console\Formatter\OutputFormatterStyle:private] =>
                                                        )

                                                )

                                        )

                                )

                            [consoleSectionOutputs:Symfony\Component\Console\Output\ConsoleOutput:private] => Array
                                (
                                )

                            [stream:Symfony\Component\Console\Output\StreamOutput:private] => Resource id #241
                            [verbosity:Symfony\Component\Console\Output\Output:private] => 32
                            [formatter:Symfony\Component\Console\Output\Output:private] => Symfony\Component\Console\Formatter\OutputFormatter Object
                                (
                                    [decorated:Symfony\Component\Console\Formatter\OutputFormatter:private] => 1
                                    [styles:Symfony\Component\Console\Formatter\OutputFormatter:private] => Array
                                        (
                                            [error] => Symfony\Component\Console\Formatter\OutputFormatterStyle Object
                                                (
                                                    [foreground:Symfony\Component\Console\Formatter\OutputFormatterStyle:private] => Array
                                                        (
                                                            [set] => 37
                                                            [unset] => 39
                                                        )

                                                    [background:Symfony\Component\Console\Formatter\OutputFormatterStyle:private] => Array
                                                        (
                                                            [set] => 41
                                                            [unset] => 49
                                                        )

                                                    [href:Symfony\Component\Console\Formatter\OutputFormatterStyle:private] =>
                                                    [options:Symfony\Component\Console\Formatter\OutputFormatterStyle:private] => Array
                                                        (
                                                        )

                                                    [handlesHrefGracefully:Symfony\Component\Console\Formatter\OutputFormatterStyle:private] =>
                                                )

                                            [info] => Symfony\Component\Console\Formatter\OutputFormatterStyle Object
                                                (
                                                    [foreground:Symfony\Component\Console\Formatter\OutputFormatterStyle:private] => Array
                                                        (
                                                            [set] => 32
                                                            [unset] => 39
                                                        )

                                                    [background:Symfony\Component\Console\Formatter\OutputFormatterStyle:private] =>
                                                    [href:Symfony\Component\Console\Formatter\OutputFormatterStyle:private] =>
                                                    [options:Symfony\Component\Console\Formatter\OutputFormatterStyle:private] => Array
                                                        (
                                                        )

                                                    [handlesHrefGracefully:Symfony\Component\Console\Formatter\OutputFormatterStyle:private] =>
                                                )

                                            [comment] => Symfony\Component\Console\Formatter\OutputFormatterStyle Object
                                                (
                                                    [foreground:Symfony\Component\Console\Formatter\OutputFormatterStyle:private] => Array
                                                        (
                                                            [set] => 33
                                                            [unset] => 39
                                                        )

                                                    [background:Symfony\Component\Console\Formatter\OutputFormatterStyle:private] =>
                                                    [href:Symfony\Component\Console\Formatter\OutputFormatterStyle:private] =>
                                                    [options:Symfony\Component\Console\Formatter\OutputFormatterStyle:private] => Array
                                                        (
                                                        )

                                                    [handlesHrefGracefully:Symfony\Component\Console\Formatter\OutputFormatterStyle:private] =>
                                                )

                                            [question] => Symfony\Component\Console\Formatter\OutputFormatterStyle Object
                                                (
                                                    [foreground:Symfony\Component\Console\Formatter\OutputFormatterStyle:private] => Array
                                                        (
                                                            [set] => 30
                                                            [unset] => 39
                                                        )

                                                    [background:Symfony\Component\Console\Formatter\OutputFormatterStyle:private] => Array
                                                        (
                                                            [set] => 46
                                                            [unset] => 49
                                                        )

                                                    [href:Symfony\Component\Console\Formatter\OutputFormatterStyle:private] =>
                                                    [options:Symfony\Component\Console\Formatter\OutputFormatterStyle:private] => Array
                                                        (
                                                        )

                                                    [handlesHrefGracefully:Symfony\Component\Console\Formatter\OutputFormatterStyle:private] =>
                                                )

                                        )

                                    [styleStack:Symfony\Component\Console\Formatter\OutputFormatter:private] => Symfony\Component\Console\Formatter\OutputFormatterStyleStack Object
                                        (
                                            [styles:Symfony\Component\Console\Formatter\OutputFormatterStyleStack:private] => Array
                                                (
                                                )

                                            [emptyStyle:Symfony\Component\Console\Formatter\OutputFormatterStyleStack:private] => Symfony\Component\Console\Formatter\OutputFormatterStyle Object
                                                (
                                                    [foreground:Symfony\Component\Console\Formatter\OutputFormatterStyle:private] =>
                                                    [background:Symfony\Component\Console\Formatter\OutputFormatterStyle:private] =>
                                                    [href:Symfony\Component\Console\Formatter\OutputFormatterStyle:private] =>
                                                    [options:Symfony\Component\Console\Formatter\OutputFormatterStyle:private] => Array
                                                        (
                                                        )

                                                    [handlesHrefGracefully:Symfony\Component\Console\Formatter\OutputFormatterStyle:private] =>
                                                )

                                        )

                                )

                        )

                )

        )

)

**Comment by haohetao** [comment]
I am commented these code.
![QQ截图20200708192909](https://user-images.githubusercontent.com/4592571/86913637-840a4a00-c151-11ea-9d6f-ff629dc6751b.png)
![QQ截图20200708192855](https://user-images.githubusercontent.com/4592571/86913646-85d40d80-c151-11ea-9805-7e52b08ebc9c.png)

**Comment by dantleech** [comment]
I pushed a fix for the AbsolutePathCandidate one https://github.com/phpactor/config-loader/commit/2962044a76d87dd60896bba060b2c0c6b7ece69d

But for the first is more tricky, and without a test setup not sure how to proceed: we expect either a URI `file:///path/to/my/thing` or a unix path `/path/to/my/thing` and the `parse_uri` will interpret windows path with `c` as the scheme and fail.

So, probably need to introduce some custom logic to detect a window path.

THe

**Comment by haohetao** [comment]
C:\Users\hetao\.vim\plugged\phpactor>php bin\phpactor status -vvv

In TextDocumentUri.php line 45:

  [Phpactor\TextDocument\Exception\InvalidUriException]
  Only "file://" scheme is supported, got "C"


Exception trace:
  at C:\Users\hetao\.vim\plugged\phpactor\vendor\phpactor\text-document\lib\TextDocumentUri.php:45
 Phpactor\TextDocument\TextDocumentUri::fromString() at C:\Users\hetao\.vim\plugged\phpactor\vendor\phpactor\file-path-resolver-extension\lib\FilePathResolverExtension.php:132
 Phpactor\FilePathResolverExtension\FilePathResolverExtension::calculateProjectId() at C:\Users\hetao\.vim\plugged\phpactor\vendor\phpactor\file-path-resolver-extension\lib\FilePathResolverExtension.php:102
 Phpactor\FilePathResolverExtension\FilePathResolverExtension->Phpactor\FilePathResolverExtension\{closure}() at C:\Users\hetao\.vim\plugged\phpactor\vendor\phpactor\container\lib\PhpactorContainer.php:79
 Phpactor\Container\PhpactorContainer->get() at C:\Users\hetao\.vim\plugged\phpactor\vendor\phpactor\file-path-resolver-extension\lib\FilePathResolverExtension.php:95
 Phpactor\FilePathResolverExtension\FilePathResolverExtension->Phpactor\FilePathResolverExtension\{closure}() at C:\Users\hetao\.vim\plugged\phpactor\vendor\phpactor\container\lib\PhpactorContainer.php:79
 Phpactor\Container\PhpactorContainer->get() at C:\Users\hetao\.vim\plugged\phpactor\vendor\phpactor\file-path-resolver-extension\lib\FilePathResolverExtension.php:67
 Phpactor\FilePathResolverExtension\FilePathResolverExtension->Phpactor\FilePathResolverExtension\{closure}() at C:\Users\hetao\.vim\plugged\phpactor\vendor\phpactor\container\lib\PhpactorContainer.php:79
 Phpactor\Container\PhpactorContainer->get() at C:\Users\hetao\.vim\plugged\phpactor\vendor\phpactor\source-code-filesystem-extension\lib\SourceCodeFilesystemExtension.php:95
 Phpactor\Extension\SourceCodeFilesystem\SourceCodeFilesystemExtension->projectRoot() at C:\Users\hetao\.vim\plugged\phpactor\vendor\phpactor\source-code-filesystem-extension\lib\SourceCodeFilesystemExtension.php:69
 Phpactor\Extension\SourceCodeFilesystem\SourceCodeFilesystemExtension->Phpactor\Extension\SourceCodeFilesystem\{closure}() at C:\Users\hetao\.vim\plugged\phpactor\vendor\phpactor\container\lib\PhpactorContainer.php:79
 Phpactor\Container\PhpactorContainer->get() at C:\Users\hetao\.vim\plugged\phpactor\vendor\phpactor\source-code-filesystem-extension\lib\SourceCodeFilesystemExtension.php:53
 Phpactor\Extension\SourceCodeFilesystem\SourceCodeFilesystemExtension->Phpactor\Extension\SourceCodeFilesystem\{closure}() at C:\Users\hetao\.vim\plugged\phpactor\vendor\phpactor\container\lib\PhpactorContainer.php:79
 Phpactor\Container\PhpactorContainer->get() at C:\Users\hetao\.vim\plugged\phpactor\lib\Extension\Core\CoreExtension.php:134
 Phpactor\Extension\Core\CoreExtension->Phpactor\Extension\Core\{closure}() at C:\Users\hetao\.vim\plugged\phpactor\vendor\phpactor\container\lib\PhpactorContainer.php:79
 Phpactor\Container\PhpactorContainer->get() at C:\Users\hetao\.vim\plugged\phpactor\lib\Extension\Core\CoreExtension.php:87
 Phpactor\Extension\Core\CoreExtension->Phpactor\Extension\Core\{closure}() at C:\Users\hetao\.vim\plugged\phpactor\vendor\phpactor\container\lib\PhpactorContainer.php:79
 Phpactor\Container\PhpactorContainer->get() at C:\Users\hetao\.vim\plugged\phpactor\vendor\symfony\console\CommandLoader\ContainerCommandLoader.php:45
 Symfony\Component\Console\CommandLoader\ContainerCommandLoader->get() at C:\Users\hetao\.vim\plugged\phpactor\vendor\phpactor\console-extension\lib\PhpactorCommandLoader.php:11
 Phpactor\Extension\Console\PhpactorCommandLoader->get() at C:\Users\hetao\.vim\plugged\phpactor\vendor\symfony\console\Application.php:541
 Symfony\Component\Console\Application->has() at C:\Users\hetao\.vim\plugged\phpactor\vendor\symfony\console\Application.php:634
 Symfony\Component\Console\Application->find() at C:\Users\hetao\.vim\plugged\phpactor\vendor\symfony\console\Application.php:235
 Symfony\Component\Console\Application->doRun() at C:\Users\hetao\.vim\plugged\phpactor\lib\Application.php:53
 Phpactor\Application->doRun() at C:\Users\hetao\.vim\plugged\phpactor\vendor\symfony\console\Application.php:147
 Symfony\Component\Console\Application->run() at C:\Users\hetao\.vim\plugged\phpactor\bin\phpactor:41

**Comment by benyaminl** [comment]
> 
> 
> I don't have Windows, so it's difficult for me to address this issue. It would be good to run the `status` command with `-vvv` to get the stack trace, I could then try and fix the issue and we can iterate on any other similar problems that turn up.

```powershell
PS C:\Users\Ben> phpactor status -vvv

In AbsolutePathCandidate.php line 27:

  [RuntimeException]
  Path is not absolute "C:\Users\Ben/.phpactor.json"


Exception trace:
  at C:\Users\Ben\AppData\Roaming\Composer\vendor\phpactor\config-loader\lib\Adapter\PathCandidate\AbsolutePathCandidate.php:27
 Phpactor\ConfigLoader\Adapter\PathCandidate\AbsolutePathCandidate->__construct() at C:\Users\Ben\AppData\Roaming\Composer\vendor\phpactor\config-loader\lib\ConfigLoaderBuilder.php:52
 Phpactor\ConfigLoader\ConfigLoaderBuilder->addCandidate() at C:\Users\Ben\AppData\Roaming\Composer\vendor\phpactor\phpactor\lib\Phpactor.php:70
 Phpactor\Phpactor::boot() at C:\Users\Ben\AppData\Roaming\Composer\vendor\phpactor\phpactor\lib\Application.php:111
 Phpactor\Application->initialize() at C:\Users\Ben\AppData\Roaming\Composer\vendor\phpactor\phpactor\lib\Application.php:38
 Phpactor\Application->doRun() at C:\Users\Ben\AppData\Roaming\Composer\vendor\symfony\console\Application.php:147
 Symfony\Component\Console\Application->run() at C:\Users\Ben\AppData\Roaming\Composer\vendor\phpactor\phpactor\bin\phpactor:42
```

**Comment by passerbyxp** [comment]
> 
> 
> I pushed a fix for the AbsolutePathCandidate one [phpactor/config-loader@2962044](https://github.com/phpactor/config-loader/commit/2962044a76d87dd60896bba060b2c0c6b7ece69d)
> 
> But for the first is more tricky, and without a test setup not sure how to proceed: we expect either a URI `file:///path/to/my/thing` or a unix path `/path/to/my/thing` and the `parse_uri` will interpret windows path with `c` as the scheme and fail.
> 
> So, probably need to introduce some custom logic to detect a window path and canonicalize it (with `Webmozart\PathUtil\Path:cannonicalize($path)`)
> 
> The relevant code is [here](https://github.com/phpactor/text-document/blob/master/lib/TextDocumentUri.php#L26) if you want to try and implement it and see if you can get Phpactor working on Windows (I'd hope that this would cover most of the cases ... but not sure)

I just clean-clone the repo (default branch: develop) and this "Path is not absolute" error is still present, making `phpactor` completely unusable in Windows.

In most case I prefer using `DIRECTORY_SEPARATOR` instead of hard-coded `/` when I'm dealing with filesystem paths, but if it's necessary to use `/` (like `AbsolutePathCandidate.php` did),

    file://d:/folder/filename.ext

is a valid path string in windows and `parse_url` can correctly understand it:

    D:\workspace>php -r "print_r(parse_url('file://d:/folder/filename.ext'));"

```
Array
(
    [scheme] => file
    [host] => d
    [path] => /folder/filename.ext
)
```

This may still affects a lot of code, but at least it allow `/` to be used across major platforms.

**Comment by dantleech** [comment]
ii;m not sure what the status of Windows support with Phpactor is currently, I assume it works in WSL anyway, closing this as old.
